version: "2"

services:
  mysql:
    container_name: mysql
    image: "mysql:5.7"
    restart: always
    mem_limit: 1G
    ports:
      - 3306:3306
    volumes:
      - './db-data/varlib:/var/lib/mysql/'
      - './db-data/varlog:/var/log/mysql/'
      - './db-data/tmp:/tmp/'
      - './db-conf:/etc/mysql/'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      local:
        ipv4_address: 172.172.0.10

networks:
  local:
    driver: bridge
    ipam:
      config:
        - subnet: 172.172.0.8/29
          gateway: 172.172.0.9